### ISSUE TITLE
KeyError 'Name'

### ISSUE THREAD

**Issue by wangyingquan** [Pengeace/lncRNA-disease-link#1]
Thank you for your work.
When I run this program, there is a error message which is showed as "KeyError:'Name'".
And I find out the error appear when process "lncRNA_disease.csv" using order "ld['Name']"(ld=pandas.read_csv(lncRNA_disease_path)).
Could you help me find out the error reason?t

**Comment by Pengeace** [comment]
Have you fixed the problem? I havn't reproduced it in my environment. 
Since `ld` is a DataFrame in Pandas, `ld['Name']` is to get the data in `'Name'` column of file _lncRNA_disease.csv_. Please check that is there exists a `'Name'` column in your used _lncRNA_disease.csv_.

The code were written and tested using Pandas 0.23 in Windows OS. If you are using Pandas with version above 1.0.0, please replace `.ix[,]` with `.loc[,]` or degrade you Pandas version to below 1.0.0 using environment managing tools like Anaconda.

If the probem still occurs in your enrivonment, please provide your python running environment information and point out the script you were testing.

**Comment by wangyingquan** [comment]
Thank you for your reply patiently. 
I had fixed the problem. I find a space is appear in the index 'Name' in lncRNA_disease.csv , like 
' Name'. So the order ld['Name'] can't work .

**Comment by Pengeace** [comment]
OK, that's fine.
